name: password_manager
description: 密码管理器

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # 吐司
  fluttertoast: ^3.1.3
  # 系统自带数据库
  sqflite: ^1.1.8
  # json 转 dart model
  json_model: ^0.0.2
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  # 加密
  flutter_string_encryption: ^0.3.1
  # 保存数据
  shared_preferences: ^0.4.2
  # 无限加载 ListView
  infinite_listview: ^1.0.1
  flukit: 1.0.2
  provider: 3.2.0
  # 下来刷新上拉加载
  pull_to_refresh: ^1.5.7
  # 网络请求
  dio: ^3.0.7
  # 指纹验证
  local_auth: ^0.5.2+3
  get_it: ^1.0.3+2
  # 获取版本信息
  package_info: ^0.4.0+12
  # 用于启动浏览器更新app
  url_launcher: ^5.2.7
  # 用于国际化，而intl包主要是引用和加载intl_translation生成后的dart代码
  intl: ^0.15.7
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  # 主要包含了一些工具，它在开发阶段主要主要的作用是从代码中提取要国际化的字符串到单独的arb文件
  # 和根据arb文件生成对应语言的dart代码，而intl包主要是引用和加载intl_translation生成后的dart代码
  intl_translation: ^0.17.2


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - imgs/ic_launcher.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
